#!/bin/env bash

# HINT: You can test the result of script using following command
# echo "1 + 1" | ./calculator

# Read expression from stdin
read -r expression

# Calculate result using bc (supports +, -, *, /)
result=$(echo "$expression" | bc)

echo "$result"
